### ISSUE TITLE
Constraint on width of CKEditor

### ISSUE THREAD

**Issue by larry-tx** [2amigos/yii2-ckeditor-widget#10]
I've got CKEditor displaying and functioning correctly using your widget. Unfortunately, what I've got is a miniscule, very narrow editor. Looking at the source code, I found that the editor is contained within a div with this specification `<div class="col-sm-6 col-sm-offset-3">`. I've tried going through your widget code and can't find where this is set, and none of the parameter settings that I've been able to intuit or imagine tell me how to correct this weird setting. (Your instructions don't include what settings will work, and the comments in your widget code don't provide much if anything.) What I want is to have the editor's div setup as `<div class="col-lg-12">`. (The editor will never be used on a mobile device or anything else with a small screen.)

How can I achieve this?

It would also be helpful to know how to make changes to the CKEditor.config settings. In particular, I need to change the CKEditor.config.uiColor setting. I've tried to do this in the config.js for CKEditor, in your widgets\full.php (I'm using the full preset), and as a last resort, tried doing a CKEditor.replace in the _form.php file itself. They all seem somehow to get trounced in the widget generation and produce no effect whatsoever.

**Comment by rahulsinh** [comment]
@tonydspaniard  I have install 2amigos/yii2-ckeditor-widget but it is not showing html tegs only simple ckeditor showing plz help me

**Comment by nikdow** [comment]
@tonydspaniard thanks for this answer, very helpful and I admire your patience with people who want to spit the dummy very publicly at the first hurdle.
