### ISSUE TITLE
How to get more plugins to work?

### ISSUE THREAD

**Issue by logofakt** [2amigos/yii2-ckeditor-widget#100]
Just played around with other extensions like autolink or autoembed. I did it exactly in the way you showed for pbckcode (which works for me!).

    <?php $this->registerJs("CKEDITOR.plugins.addExternal('pbckcode', '/pbckcode/plugin.js', '');"); ?>
    <?php $this->registerJs("CKEDITOR.plugins.addExternal('autolink', '/autolink/plugin.js', '');"); ?>
    ...
    'extraPlugins' => ['pbckcode', 'autolink'],
    ...
    ['name' => 'pbckcode'], // <--- OUR NEW PLUGIN YAY!

With this configuration the editbox will not render.

If I comment out all of pbckcode only having autolink I can't paste any text into the editbox. Could it be that other plugins do not work? Or did I misconfig something?

**Comment by s4pphir3** [comment]
Not sure if you still need it but it might help someone in future. You need to use config string as described here: [CKEditor Documentation](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-extraPlugins). In your case:
'extraPlugins' => 'pbckcode,autolink',

**Comment by tonydspaniard** [comment]
Thank you @s4pphir3
