### ISSUE TITLE
unable to load texttransform plugin

### ISSUE THREAD

**Issue by ak868308** [2amigos/yii2-ckeditor-widget#103]
Can you please help for implementing texttransform plugin. 
ckeditor.js seems not updated! 

It is good for me if you explain with example.

Thanks

**Comment by tonydspaniard** [comment]
Can you show me your code? This was added to the README: https://github.com/2amigos/yii2-ckeditor-widget#how-to-add-custom-plugins

**Comment by tonydspaniard** [comment]
ping

**Comment by tonydspaniard** [comment]
No more info given. Closing this issue.
