### ISSUE TITLE
__DIR__ concatenation error

### ISSUE THREAD

**Issue by singleton90** [2amigos/yii2-ckeditor-widget#104]
/vendor/2amigos/yii2-ckeditor-widget/src/CKEditorWidgetAsset.php on 21 line generates error 

> syntax error, unexpected '.', expecting ',' or ';'

```class CKEditorWidgetAsset extends AssetBundle
{
    public $sourcePath = __DIR__ . '/assets';

    public $depends = [
        'dosamigos\ckeditor\CKEditorAsset'
    ];

    public $js = [
        'dosamigos-ckeditor.widget.js'
    ];
}```

**Comment by tonydspaniard** [comment]
?

Where is the error?

**Comment by MysteryDragon** [comment]
It's obviously error from PHP 5.4 / 5.5 'cause constant expressions became available since 5.6.
But this code is fixed in actual version, so it seems like updating will help :)

**Comment by loop69** [comment]
Hi!
I upgraded php to 5.6.30, but the error remained ...

**Comment by MysteryDragon** [comment]
@loop69 or you can try update your yii2-ckeditor-widget plugin version.
This issue related to **old** version of this plugin.

**Comment by loop69** [comment]
I installed this plugin from github by composer two days ago. So, I think it must be newest...

**Comment by MysteryDragon** [comment]
@loop69 the thing is that there are not such code in actual version: https://github.com/2amigos/yii2-ckeditor-widget/blob/60e4d2dbb138706c8c2195a1b29c420bda044b19/src/CKEditorWidgetAsset.php#L21
Maybe there was old version in instructions, or old version stored in `composer.lock`... Strange :)
