### ISSUE TITLE
Editor not show

### ISSUE THREAD

**Issue by hfageeh** [2amigos/yii2-ckeditor-widget#108]
<img width="960" alt="error1" src="https://cloud.githubusercontent.com/assets/6096313/25303170/0875d58c-2756-11e7-816c-cb6a93b30f70.png">

**Comment by tonydspaniard** [comment]
Can you show your code? On another note, can you open "Chrome developer tools" and see if there is any error?

**Comment by reachz** [comment]
dear, hfageeh
i got a problem like you.

so you need to open "Chrome developer tools" in Console tab if you got an error like
 "styles.js is missing form whatever in youprojectname\frontendorbackend\web\assets\xxxxx\styles.js" 

how to fix it 
  1. go to yourproject\vendor\ckeditor\ckeditor  copy all of them to 
      youprojectname\frontendorbackend\web\assets\xxxxx\
  2. refresh you page

that solves my problem.

**Comment by tonydspaniard** [comment]
Thanks @reachz but that means that the asset bundle wasn't registered. Was that your case?
