### ISSUE TITLE
JS Errors with latest

### ISSUE THREAD

**Issue by Lewke** [2amigos/yii2-ckeditor-widget#114]
Hi, using the latest version of the widget, we can never get our CKEditor to load onto the page properly.

We use a custom toolbar to hide unneeded icons.
We only have 2 plugins included: embed, embedbase.
Javascript shows the following error:

Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "notificationaggregator"
or
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "widget" was not found 

depending on what it feels like on that particular page load.

We think it could be caused by using the full preset version of ckeditor as opposed to v4.7.1 (as the plugin list is different) on its own, any advice on how to get it working would be appreciated.

**Comment by tonydspaniard** [comment]
Apologies for such issue. Have you tried to install the missing plugin manually like explained on the docs?

**Comment by Lewke** [comment]
Thanks for getting back to us :)

We haven't because of a few reasons:

1) We didn't want to introduce so many manual dependencies
2) Fixing one will likely lead to needing another, and another, and another
3) We'd had things working previously and only updated to these latest releases to use plugins, so were hoping it was an issue with this widget that would be resolved fairly quickly.

If nothing is going to be changed then we'll have to bring in all the plugins that are necessary and hope that resolves the issues.

Thanks!

**Comment by tonydspaniard** [comment]
Hi @Lewke,

Latest modification were mostly with the issues with bring in the full version with composer (ckeditor had the issue which was finally resolved). You can safely use the version that worked for you.

**Comment by Lewke** [comment]
Unfortunately we cant, unless you can suggest a version that had the full suite of plugins as well as the ability to add in custom plugins?

**Comment by tonydspaniard** [comment]
@Lewke please, list the plugins you need and I'll check what is the actual version. I may version tag for you that version.

**Comment by Lewke** [comment]
we just use embed and embedbase, i don't think they're in any of the presets, only the complete versions of ckeditor. It's ok, we're going to bring in the manual dependencies for now, thanks for your help :)

**Comment by tonydspaniard** [comment]
@Lewke you are totally right.  CKEditor is quite messy in terms of plugins, all the plugins are seen on "master" but then versioning modifies its inclusions, which is quite weird. Nevertheless, I believe is actually best to manually install them. 

Best regards
