### ISSUE TITLE
Multiple requests css assets

### ISSUE THREAD

**Issue by markux** [2amigos/yii2-ckeditor-widget#115]
Hi, I've 20 input on one page, all like this:

`<?= $form->field($model, 'principle_en')->widget(\dosamigos\ckeditor\CKEditor::className(), [ 'clientOptions' => ['height' => 200], 'preset' => 'standard']) ?>`

and each one make a request for content.css and tableselection.css file: is there a manner to avoid these requests?

**Comment by tonydspaniard** [comment]
@markux strange as the asset bundle classes included do not have those sources. It seems is part of a plugin? How do you register that plugin? Can you please elaborate a bit further your question with more code? Thanks!

**Comment by markux** [comment]
@tonydspaniard I found contents.css only in ckeditor.js 

`CKEDITOR.getUrl("contents.css"),`

so I need to deep into how it works.
thanks
