### ISSUE TITLE
Is there any option to define ClientEvents

### ISSUE THREAD

**Issue by ak868308** [2amigos/yii2-ckeditor-widget#116]
Hi

I there any options to define runtime event like keyup? using clientEvents property?

**Comment by tonydspaniard** [comment]
Add to the `clientOptions` property the following: 
```php 
// .... other settings

'on' = > [
    'change' => new JsExpression('function (evt) { console.log(evt);}')
]
// .... other settings
```

Check here for example in JS: https://jsfiddle.net/oleq/xfvrA/
