### ISSUE TITLE
Several toolbar not show

### ISSUE THREAD

**Issue by ipanardian** [2amigos/yii2-ckeditor-widget#12]
Many Several toolbar not show. Like forms, align, colors etc. I used full preset. 

'toolbarGroups' => [
		['name' => 'document', 'groups' => ['mode', 'document', 'doctools']],
		['name' => 'clipboard', 'groups' => ['clipboard', 'undo']],
		['name' => 'editing', 'groups' => [ 'find', 'selection', 'spellchecker']],
		['name' => 'forms'],
		'/',
		['name' => 'basicstyles', 'groups' => ['basicstyles', 'colors','cleanup']],
		['name' => 'paragraph', 'groups' => [ 'list', 'indent', 'blocks', 'align', 'bidi' ]],
		['name' => 'links'],
		['name' => 'insert'],
		'/',
		['name' => 'styles'],
		['name' => 'blocks'],
		['name' => 'colors'],
		['name' => 'tools'],
		['name' => 'others'],
	],

**Comment by tonydspaniard** [comment]
@philippfrenzel seems that its your styles... fixing the full preset, icons display correctly: 

![captura de pantalla 2015-03-02 a la s 10 29 28](https://cloud.githubusercontent.com/assets/566016/6438177/1f0853c6-c0c7-11e4-91b9-9822b2300c88.png)

**Comment by caceresvega** [comment]
Hi I have the same problem, I made corruption and cleared the browser cache and yet so I do not get to show all buttons, any idea how to fix it?
thanks
