### ISSUE TITLE
HTML tags when saving to db

### ISSUE THREAD

**Issue by sgaita** [2amigos/yii2-ckeditor-widget#122]
How does one strip of the html tags when saving to database.
example: I have my content formatted to look like 
=> _Consists of all policy_ __**_brief_**__ documents . but i am getting this instead
![scree](https://user-images.githubusercontent.com/16446134/35475513-d54de6b2-03b0-11e8-97bf-ad3c99c2c01e.jpg)

**Comment by tonydspaniard** [comment]
You could use `strip_tags` before saving to the database: https://www.php.net/manual/en/function.strip-tags.php
