### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by dPhantum** [2amigos/yii2-ckeditor-widget#124]
What to do about this error amigos?

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package ckeditor/ckeditor (locked at 4.8.0, required as 4.7.3) is satisfiable by ckeditor/ckeditor[4.8.0] but these conflict with your requirements or minimum-stability.
Installation failed, reverting ./composer.json to its original content.

**Comment by tonydspaniard** [comment]
Try with this in your composer file:

```
"minimum-stability" : "dev",
"prefer-stable": true
