### ISSUE TITLE
Current constraint prevents updating

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-ckeditor-widget#126]
This PR https://github.com/2amigos/yii2-ckeditor-widget/pull/113 breaks the updating of the bower package like discussed in https://github.com/2amigos/yii2-ckeditor-widget/pull/96

I think it should be `^4.7`, if you need a special version (`dev-full`), you need to specify it in your project.

**Comment by tonydspaniard** [comment]
Thanks @schmunk42 so, should we update the constrain again to `^4.7`? would that affect presets?

**Comment by schmunk42** [comment]
I don't know about presets, but as said above, if you need something like `-full` you need to do it in your project, because it's not understood by composer, at least not as a stable version.

**Comment by tonydspaniard** [comment]
Is already changed. Thanks @schmunk42
