### ISSUE TITLE
Unable to change default font

### ISSUE THREAD

**Issue by sparkyway** [2amigos/yii2-ckeditor-widget#129]
Extension version: 2.1.0

Unable to set default font for the editor according to its documentation (font_style, https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-font_style), the font does not change

![image](https://user-images.githubusercontent.com/37216916/44419210-0d1e3500-a56a-11e8-8e15-c42c6f86df42.png)

**Comment by tonydspaniard** [comment]
How do you add the font? Have you tried https://stackoverflow.com/a/25744119

**Comment by tonydspaniard** [comment]
Closing for not response.
