### ISSUE TITLE
Problem in adding extra plugin

### ISSUE THREAD

**Issue by baltechies** [2amigos/yii2-ckeditor-widget#130]
Hi,
I have followed the **How to add custom plugins** documentation to add the extra plugin sourcearea. But button is not visible in toolbaar.

**Comment by Aribros** [comment]
Could you post your sample code?

**Comment by baltechies** [comment]
I was able to find the solution.

**Comment by tonydspaniard** [comment]
@baltechies may you share your solution if it wasn't part of our docs? that may help others.
