### ISSUE TITLE
Class 'dosamigos\ckeditor\CKEditor' not found

### ISSUE THREAD

**Issue by DarkSlash** [2amigos/yii2-ckeditor-widget#131]
I install it using composer require 2amigos/yii2-ckeditor-widget but when I try to use it in a view, I get the error "Class 'dosamigos\ckeditor\CKEditor' not found". At the beginning of the file I wrote use dosamigos\ckeditor\CKEditor; and I see the files on the vendor/dosamigos folder.

**Comment by bhushanlambat** [comment]
I am facing same Issue ... Any solutionssss....?

**Comment by DarkSlash** [comment]
I found the solution! I installed the plugin by composer... in the backend folder. This must be installed on the root folder to work. I though I could just install it for backend, but doesn't work that way.

**Comment by Aribros** [comment]
Since you found the solution, I will closing this issue.

**Comment by ntpthao** [comment]
> Since you found the solution, I will closing this issue.
excuse me, how to install the plugin by composer in the backend folder???
Can you guide me specifically?

**Comment by tonydspaniard** [comment]
@ntpthao the plugin when used with composer, you simply need to insert it into the page you use by adding the namespace. 

The composer.json file *must* be at the root of your project and then, insert the autoload on your index files. Yii already does that for you: https://github.com/yiisoft/yii2-app-advanced/blob/master/environments/dev/backend/web/index.php#L5
