### ISSUE TITLE
how can I do a custom preset or remove some buttons from basic?

### ISSUE THREAD

**Issue by rizrob66** [2amigos/yii2-ckeditor-widget#132]
please help me, I need a custom preset or remove some buttons from basic?
riz

**Comment by Aribros** [comment]
See declare preset as "custom", then add/remove the necessary cofiguration in the clientOptions array. See the example code below.

`    <?= $form->field($model, 'message')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'custom',
        'clientOptions' => [
            'height' => 400,
            'toolbarGroups' => [
                ['name' => 'undo'],
                ['name' => 'basicstyles', 'groups' => ['basicstyles', 'cleanup']],
                ['name' => 'colors'],
                ['name' => 'links', 'groups' => ['links', 'insert']],
                ['name' => 'others', 'groups' => ['others', 'about']],
            ],
            'removeButtons' => 'Subscript,Superscript,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe',
            'removePlugins' => 'elementspath',
            'resize_enabled' => false
        ]
    ]) ?> `

**Comment by Aribros** [comment]
See declare preset as "custom", then add/remove the necessary cofiguration in the clientOptions array. See the example code below.
```
    <?= $form->field($model, 'message')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'custom',
        'clientOptions' => [
            'height' => 400,
            'toolbarGroups' => [
                ['name' => 'undo'],
                ['name' => 'basicstyles', 'groups' => ['basicstyles', 'cleanup']],
                ['name' => 'colors'],
                ['name' => 'links', 'groups' => ['links', 'insert']],
                ['name' => 'others', 'groups' => ['others', 'about']],
            ],
            'removeButtons' => 'Subscript,Superscript,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe',
            'removePlugins' => 'elementspath',
            'resize_enabled' => false
        ]
    ]) ?> 

```
