### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by MohammedAbir** [2amigos/yii2-ckeditor-widget#14]
I used this code

<?= $form->field($model, 'information')->widget(CKEditor::className(),[
					'editorOptions' => [
						'preset' => 'full', 
						'inline' => false, 
						//'filebrowserBrowseUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test',['type'=>'Images']),
						'filebrowserUploadUrl'=>Yii::$app->getUrlManager()->createUrl('dashboard/test')
					],
				]);?>

but this is not working 

if fixed it please help

**Comment by evilgamerkra** [comment]
I am also facing the same issue of image upload in yii2-ckeditor. Is there any solution to the problem on how to upload image in yii2-ckeditor ?

**Comment by mtangoo** [comment]
@tonydspaniard  I found this, I think might help.
http://www.yiiframework.com/extension/yii2-kcfinder/

**Comment by tonydspaniard** [comment]
Guys, I am truly sorry for not being really responsive. I am refactoring our site + the inclusion of all the documentation of all our extensions (as I did promised in the past). This way the support would be better. 

I will fix the issues of this extension as soon as I finish my current work.

**Comment by mtangoo** [comment]
I'm working on my extension to add functionality. Hope I will contribute back here whatever I learn to make it support Uploading (Images only for me)

**Comment by tonydspaniard** [comment]
@MohammedAbir @mtangoo we are in the process of refactoring our site, and also all our extensions. When is time to refactor the structure of this one (following the https://github.com/2amigos/yii2-extension-skeleton), I will fix the image upload.

**Comment by tonydspaniard** [comment]
@mtangoo @MohammedAbir Its fixed with latest update, check "master" branch, will update version patch asap.

This is the way to do it: 

```php 
<?=
        $form->field($model, 'password')->widget(
            \dosamigos\ckeditor\CKEditor::className(),
            [
                'preset' => 'basic',
                'clientOptions' => [
                    'filebrowserUploadUrl' => 'site/url'
                ]
            ]
        ); ?>
![Uploading Captura de pantalla 2015-03-02 a la(s) 10.40.14.png . . .]()

```

**Comment by engrashid** [comment]
Thanks for the fix .
Will try shortly .

**Comment by MohammedAbir** [comment]
Thanks bro

**Comment by mtangoo** [comment]
I just opened GitHub with cheering heart. Time to dump my own and use this one.
One thing, what about Image Uploading? Is it included in this update too?

**Comment by tonydspaniard** [comment]
@MohammedAbir  yep... it does but you have to write your own action to upload it.

**Comment by mtangoo** [comment]
Rolled simple article on this
My Yii2/CKeditor Article
http://hosannahighertech.co.tz/blog/mweledi/11-Yii2-CKEditor-and-Images-Upload

**Comment by tonydspaniard** [comment]
@mtangoo thank you so much! Keep up the good work!

**Comment by mtangoo** [comment]
Thanks @tonydspaniard 
My next post on it will be an image broser. Am just hunting on free time :)

**Comment by osnwach** [comment]
CKeditor not showing on my form.
I used this code: 
<?= $form->field($model, 'comment')->widget(\dosamigos\ckeditor\CKEditor::className(),[
        'preset'=>'full',
        ]) ?>  

But I dont see the CKeditor, when I preview in Browser. Please why is it so ?

**Comment by tonydspaniard** [comment]
Was our mistake... Will fix tomorrow. Apologies. Ckeditor doesn't have full version stable. Weird but true.

**Comment by tonydspaniard** [comment]
This is fixed with latest update

**Comment by rahulsinh** [comment]
Hii everyone my ckeditor is working good now i add image upload option but when i upload image then i can not get the image url .it show the error image source url is missing how to resolve this problem.
<?=
    $form->field($model, 'description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic',
        'clientOptions' => [
                    'filebrowserUploadUrl' => 'ckeditor/url'
                ]
    ])
    ?>

this is my controller and action 
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

class CkeditorController extends Controller
{ 
    public function actionUrl()
    {         
        $uploadedFile = UploadedFile::getInstanceByName('upload'); 
        $mime = \yii\helpers\FileHelper::getMimeType($uploadedFile->tempName);
        $file = time()."_".$uploadedFile->name;
        
        $url = Yii::$app->urlManager->createAbsoluteUrl('/uploads/ckeditor/'.$file);
        
        $uploadPath = Yii::getAlias('@webroot').'/uploads/ckeditor/'.$file;
        //extensive suitability check before doing anything with the file…
        if ($uploadedFile==null)
        {
           $message = "No file uploaded.";
        }
        else if ($uploadedFile->size == 0)
        {
           $message = "The file is of zero length.";
        }
        else if ($mime!="image/jpeg" && $mime!="image/png")
        {
           $message = "The image must be in either JPG or PNG format. Please upload a JPG or PNG instead.";
        }
        else if ($uploadedFile->tempName==null)
        {
           $message = "You may be attempting to hack our server. We're on to you; expect a knock on the door sometime soon.";
        }
        else {
          $message = "";
          $move = $uploadedFile->saveAs($uploadPath);
          if(!$move)
          {
             $message = "Error moving uploaded file. Check the script is granted Read/Write/Modify permissions.";
          } 
        }
        $funcNum = $_GET['CKEditorFuncNum'] ;
        echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";        
    } 
}

**Comment by rahulsinh** [comment]
@mtangoo  please resolve my issue

**Comment by mtangoo** [comment]
why me @rahulsinh ? ;) is it because of the article? If so did you follow the comments there?
Please comment there so that I can follow your issue

**Comment by rahulsinh** [comment]
Hii everyone my ckeditor is working good now i add image upload option but when i upload image then i can not get the image url .it show the error image source url is missing how to resolve this problem.
<?=
$form->field($model, 'description')->widget(CKEditor::className(), [
'options' => ['rows' => 6],
'preset' => 'basic',
'clientOptions' => [
'filebrowserUploadUrl' => 'ckeditor/url'
]
])
?>

this is my controller and action 
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

class CkeditorController extends Controller
{ 
public function actionUrl()
{

$uploadedFile = UploadedFile::getInstanceByName('upload'); 
$mime = \yii\helpers\FileHelper::getMimeType($uploadedFile->tempName);
$file = time()."_".$uploadedFile->name;

    $url = Yii::$app->urlManager->createAbsoluteUrl('/uploads/ckeditor/'.$file);

    $uploadPath = Yii::getAlias('@webroot').'/uploads/ckeditor/'.$file;
    //extensive suitability check before doing anything with the file…
    if ($uploadedFile==null)
    {
       $message = "No file uploaded.";
    }
    else if ($uploadedFile->size == 0)
    {
       $message = "The file is of zero length.";
    }
    else if ($mime!="image/jpeg" && $mime!="image/png")
    {
       $message = "The image must be in either JPG or PNG format. Please upload a JPG or PNG instead.";
    }
    else if ($uploadedFile->tempName==null)
    {
       $message = "You may be attempting to hack our server. We're on to you; expect a knock on the door sometime soon.";
    }
    else {
      $message = "";
      $move = $uploadedFile->saveAs($uploadPath);
      if(!$move)
      {
         $message = "Error moving uploaded file. Check the script is granted Read/Write/Modify permissions.";
      } 
    }
    $funcNum = $_GET['CKEditorFuncNum'] ;
    echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";        
}

**Comment by rahulsinh** [comment]
it's working good thanx for help.image upload using ckeditor is working fine.

**Comment by mtangoo** [comment]
Enjoy!

**Comment by osnwach** [comment]
@rahulsinh, please what were you doing wrongly before ? 
And please how did you get it to work now ? This will help other people.

Regards from me !!

**Comment by rahulsinh** [comment]
@osnwach  
first i am using this code in my view file where i am using  this code for ckeditor
<?=
$form->field($model, 'description')->widget(CKEditor::className(), [
'options' => ['rows' => 6],
'preset' => 'basic',
'clientOptions' => [
'filebrowserUploadUrl' => 'ckeditor/url'
]
])
?>
so  i am not able to upload image using ckeditor after replaced this code i am sucessfully upload the image using ckeditor the new code is this put this in your view file:

 <?=
    $form->field($model, 'description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic',
        'clientOptions' => [
                    'filebrowserUploadUrl' => Url::to(['ckeditor/url'])
                ]
    ])
    ?>

**Comment by purnimasingh123** [comment]
i have image upload option but it shows error object not found although i check previous comments for sol but its not working.the exact error it shows is:
Object not found!The requested URL was not found on this server
Error 404
code i use in _from file is:
<?= $form->field($model, 'news_description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'advanced',
		'clientOptions' => [
            'filebrowserUploadUrl' => 'site/url'
			]
	  ]) ?>
In ckeditorcontroller file:
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

class CkeditorController extends Controller
{ 
public function actionUrl()
{

$uploadedFile = UploadedFile::getInstanceByName('upload'); 
$mime = \yii\helpers\FileHelper::getMimeType($uploadedFile->tempName);
$file = time()."_".$uploadedFile->name;

$url = Yii::$app->urlManager->createAbsoluteUrl('/uploads/ckeditor/'.$file);

$uploadPath = Yii::getAlias('@webroot').'/uploads/ckeditor/'.$file;
//extensive suitability check before doing anything with the file…
if ($uploadedFile==null)
{
   $message = "No file uploaded.";
}
else if ($uploadedFile->size == 0)
{
   $message = "The file is of zero length.";
}
else if ($mime!="image/jpeg" && $mime!="image/png")
{
   $message = "The image must be in either JPG or PNG format. Please upload a JPG or PNG instead.";
}
else if ($uploadedFile->tempName==null)
{
   $message = "You may be attempting to hack our server. We're on to you; expect a knock on the door sometime soon.";
}
else {
  $message = "";
  $move = $uploadedFile->saveAs($uploadPath);
  if(!$move)
  {
     $message = "Error moving uploaded file. Check the script is granted Read/Write/Modify permissions.";
  } 
}
$funcNum = $_GET['CKEditorFuncNum'] ;
echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";        
}
}

------->my ckeditor folder exist in htdocs.

**Comment by amirsabet** [comment]
hi
i use kcfinder for upload image from local to server in 2amigos/yii2-ckeditor-widget

but whene click "send it in server" i get alert with this message 
"You dont have permission to upload files"

i used xammp

PLEASE HELP ME !!!

**Comment by Harutin1991** [comment]
Hello everyone,

I have issue with image upload. I have 3 ckeditor on my form and those 3 have same upload input name.When I have trying to upload image I got empty array,.How can I change that image upload name and create 3 names for every ckeditor?

Thanks

**Comment by alexander-ronin** [comment]
@Harutin1991, nice question, I've the same.

But it seems nobody maintain this extension more than 2 years. And there is no documentation for it. Sad...
