### ISSUE TITLE
CKEditor do not save written content after first save() try

### ISSUE THREAD

**Issue by nenad-zivkovic** [2amigos/yii2-ckeditor-widget#18]
I am using your widget in my application. There is a "content" field responsible for accepting text, and in my view it is defined like this:

```
<?= $form->field($model, 'content')->widget(CKEditor::className(), 
    ['options' => ['rows' => 6],'preset' => 'full']) ?>
```

In my model there are only two rules defined for this content field: required and string.

When I write something in the CKEditor field and try to submit changes, I will get error " Content cannot be blank. " If I try to submit again ( without changing anything, just press submit button again ), everything that was written will be saved. 

If I turn off required rule, I will be able to submit form, but text that is written in CKEditor field will not be saved.

What do you think, why is this happening ?

**Comment by gmstas** [comment]
I have the same problem when i use it in my advanced yii2 on my linux server. This does not happen when i use it in yii2 basic in my localhost wamp. Can someone help?

**Comment by akorinek** [comment]
Same problem here, first save fails, gives the error that the text cannot be empty. Then the second save succeeds.

**Comment by tonydspaniard** [comment]
I know how to fix it. Bit busy atm but will fix it.

**Comment by gmstas** [comment]
adding in ActiveForm 'enableClientValidation' => false, will fix it

**Comment by karpoff** [comment]
see the same problem
'enableClientValidation' => false doesn't work. I think because of 'enableAjaxValidation' => true (I can't change it). hope fix will come soon

**Comment by tonydspaniard** [comment]
Have you guys tried with "master" version? it should have been fixed. I will update the plugin with new version patch.

**Comment by akorinek** [comment]
Yes, the master version actually fixes this, thanks.

**Comment by tonydspaniard** [comment]
Will update the version patch

**Comment by osnwach** [comment]
CKeditor not showing on my form.
I used this code: 
<?= $form->field($model, 'comment')->widget(\dosamigos\ckeditor\CKEditor::className(),[
'preset'=>'full',
]) ?>

But I dont see the CKeditor, when I preview in Browser. Please why is it so ?
