### ISSUE TITLE
Pages loaded from renderAjax does not display ckeditor

### ISSUE THREAD

**Issue by gmstas** [2amigos/yii2-ckeditor-widget#20]
When i renderAjax a page with CKeditor in one of the text field, the CKeditor does not load. It only loads for pages loaded with render

**Comment by tonydspaniard** [comment]
"renderAjax" doesnt register scripts

**Comment by gmstas** [comment]
how do i go about to make it work?

**Comment by tonydspaniard** [comment]
You need to use `render` not `renderAjax`. 

If you are displaying the editor in a modal, this is the way I do it: 

- register the required assets on the view that calls the modal 
- when the modal is call, initialize the editor via Javascript
