### ISSUE TITLE
config.baseHref not working

### ISSUE THREAD

**Issue by ipanardian** [2amigos/yii2-ckeditor-widget#26]
I've tried this way but not working.
<?= $form->field($page, 'content')->textarea()->widget(CKEditor::className(), [
        'options' => ['rows' => 5],
        'preset' => 'full',
        'clientOptions' => [
            'baseHref' => 'http://www.example.com/path/'
        ],
    ]) ?>

And I've tried edit on config.js also not working
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
};
CKEDITOR.config.baseHref =  'http://www.example.com/path/';

Could you tell the right way?
Thanks a lot before, your yii2-ckeditor-widget is helpful.

**Comment by tonydspaniard** [comment]
Strange, that should be it. 

Have you tried: 

```php 
'clientOptions' => [
    'customConfig' => 'path/to/config.js'
]
```

But is strange, `baseHref` should be fine

**Comment by tonydspaniard** [comment]
bump

**Comment by ipanardian** [comment]
Sorry late to give reply.
I use following code because the example.com will be php variable. 
'clientOptions' => [
'baseHref' => 'http://www.example.com/path/'
],

I have tried add baseHref directly like the following code just for test.
$js = "CKEDITOR.replace('$id', {baseHref: 'http://www.example.com/path/', uiColor: '#14B8C4'});";
$view->registerJs($js);

The uiColor was working but the baseHref did not.

I downloaded ckeditor_4.4.7_full, extract it and open the sample. I have tried add baseHref but did not work either. Is the problem on CKEditor?

**Comment by tonydspaniard** [comment]
@ipanardian it looks like is a problem of the plugin itself
