### ISSUE TITLE
Adding Code Highlight Plugin

### ISSUE THREAD

**Issue by mtangoo** [2amigos/yii2-ckeditor-widget#28]
I have a CKEditor extension I have been using and its having a highlightjs for Code syntax highlighting and a Pack of Emoticons for my forum. Now I want to migrate to this extension and need to know if there is easy way to add them without tampering with vendors DIR. Is there a way/plan to have them? They are pretty basic of stuffs these days

**Comment by tonydspaniard** [comment]
You can easily extend the `CKEditorAsset.php` and point to your custom `ckeditor` assets registration.

**Comment by mtangoo** [comment]
So no way to avoid it modifying sources?

**Comment by tonydspaniard** [comment]
You can do it your self. And point the override CKEditorAsset to access those. Otherwise, you have to talk to CKEditor package administrators to include those for you. I have no control over that.

**Comment by mtangoo** [comment]
I see. I was looking for Impossible. I will have to go that way!
