### ISSUE TITLE
ActiveForm and enableClientValidation=true

### ISSUE THREAD

**Issue by klevron** [2amigos/yii2-ckeditor-widget#3]
Hello

Thanks for this useful widget.

Just a little problem with ActiveForm and client validation on a required field, submit button will not trigger validation on the first time (since corresponding input is not updated). I can make a PR for this if you want.

**Comment by saadazharsaeed** [comment]
In some cases CKEDITOR creates instance like 'modelName-attribute', and if you are trying to use multiple instances of CKEDITOR on single page then this code script can be helpful:

<?php 
        $attribute = 'description';
        $js = "CKEDITOR.on('instanceCreated', function(e) {
              e.editor.on('change', function(ev) {
                  CKEDITOR.instances[e.editor.name].updateElement();
                  $('#' + ev.editor.name).trigger('change');
                  return false;
              });
          });";
        $this->registerJS($js);

        echo $form->field($model, $attribute)->widget(CKEditor::className(), [
         'options' => ['rows' => 4],
         'preset' => 'full'
        ]);
    ?>

**Comment by sbekzhan** [comment]
Who knows? How i can use Ckeditor only for tag <input> not for Active Form ?

**Comment by sbekzhan** [comment]
tag "input"
