### ISSUE TITLE
Am not able to install

### ISSUE THREAD

**Issue by merlano17** [2amigos/yii2-ckeditor-widget#32]
composer require 2amigos/yii2-ckeditor-widget:~1.0

while i run this i get error saying the dependent ckeditor dev-full/stable there is no stable version

**Comment by flotzilla** [comment]
Try to add this line to your composer.json in require segment. Ckeditor must be first in this dependency list (before widget) and 1.0.2 points on the latest version.

`"ckeditor/ckeditor": "dev-full/stable",
"2amigos/yii2-ckeditor-widget" : "1.0.2"`

**Comment by creocoder** [comment]
Dublicate of #29
