### ISSUE TITLE
.git folder

### ISSUE THREAD

**Issue by sajtosnorbert** [2amigos/yii2-ckeditor-widget#34]
Hi!

I am tríing to install my vendor folder on a shared hosting server, so only ftp is available.
My solution is to use an own git repository for all the files I need in production and then use git-ftp to upload changes.

My problem is that in your extension folder there is an other .git folder, so I can't push this to my bitbucket repository.

Is there any way to ignore the .git folder somehow (ex. in the .gitignore file)?
Or do you have a working solution, how to deploy vendor folder on shared hosing?

Thanks,
Norbert.

**Comment by tonydspaniard** [comment]
We don't, we normally use `composer install` on servers.

**Comment by creocoder** [comment]
@tonydspaniard I think we can close it since question is not relevant to extension itself.
