### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by osCMattiFinn** [2amigos/yii2-ckeditor-widget#40]
When I select 'standard' as an option for the editor it displays the toolbars on three lines.  There is enough space for these to display on a single line.

How can I make the editor do this as it looks very bad?

**Comment by anvarulugov** [comment]
I suggest you to read this issue:
https://github.com/2amigos/yii2-ckeditor-widget/issues/37

**Comment by tonydspaniard** [comment]
see #37 as suggested
