### ISSUE TITLE
Integration KCFinder

### ISSUE THREAD

**Issue by AlexMcowkin** [2amigos/yii2-ckeditor-widget#42]
Hello!
can you create new ckeditor widget with KCFinder?
thank you.

**Comment by sunftec** [comment]
tank you for yii2-ckeditor-widget
i cant upload image directly to web server with this editor..i think this very usefulllll! please take this.
tank you...

**Comment by tonydspaniard** [comment]
Afaik, CKFinder is not free?

**Comment by NabiKAZ** [comment]
@tonydspaniard

http://kcfinder.sunhater.com/
It's on GPL license.

I. DESCRIPTION

    KCFinder free open-source alternative to the CKFinder Web file manager. It
    can be integrated into FCKeditor, CKEditor, and TinyMCE WYSIWYG web
    editors or your custom web applications to upload and manage images, flash
    movies, and other files that can be embedded in an editor's generated HTML
    content. Only PHP server-side scripting is supported.


II. FEATURES

    1. Ajax engine with JSON responses.

    2. Easy to integrate and configure in web applications.

    3. Clipboard for copy and move multiple files

    4. Select multiple files with Ctrl key

    5. Download multiple files or a folder as ZIP file

    6. Resize bigger uploaded images. Configurable maximum image resolution.

    7. Configurable thumbnail resolution.

    8. Visual themes.

    9. Multilanguage system.

    10. Slideshow.

    11. Multiple files upload (ala Facebook)

    12. Drag and drop uploading

**Comment by tonydspaniard** [comment]
Have you seen my blog post about `ElFinder`? I think is better: http://2amigos.us/blog/how-to-connect-elfinder-with-amazon-s3-for-yii2 (its for S3 but you can use it without it)

**Comment by NabiKAZ** [comment]
This is for advanced users. The beginner users can not work with syntax. some time they want to copy/paste context from word!
ElFinder is a markup editor. but CKeditor is a HTML editor. and that's difference.

**Comment by NabiKAZ** [comment]
@tonydspaniard 
Maybe I can implement this project: http://kcfinder.sunhater.com/ GPL License into current `yii2-ckeditor-widget` package.
Consider  `kcfinder` is an external project and I can integrate into `ckeditor` by default and user can disable it if want.
I thinks this is benefit and required upload image in some projects.
If you agree, I work on it and I provide a PR? Otherwise, I can implement as separate package.

**Comment by NabiKAZ** [comment]
@tonydspaniard 
I'm waiting for your advice.

**Comment by tonydspaniard** [comment]
@NabiKAZ I agree... apologies for the delay and thanks for your support

**Comment by temirfe** [comment]
@NabiKAZ so did you implement? if so how to use it?

**Comment by tonydspaniard** [comment]
@temirfe I did implement the ElFinder with FlySystem on SimpleMDE Markdown, I believe you could easily create a custom button to do the same: http://www.2amigos.us/blog/how-to-connect-elfinder-with-amazon-s3-for-yii2... Apologies but I am seriously busy these days.

**Comment by NabiKAZ** [comment]
@temirfe Sorry for delay, I implement it, wait for confirm pull request.
