### ISSUE TITLE
Initilized with jquery

### ISSUE THREAD

**Issue by dubeymahi48** [2amigos/yii2-ckeditor-widget#45]
Hiii,
How can i initilized with jquery??

Text editor option is not same when i initilized with jquery and widgets provided by you.I initilized with this code. 
$("#initText").ckeditor(function() {});

Thank you in advanced.

**Comment by tonydspaniard** [comment]
For that, I would override the main class register script function: https://github.com/2amigos/yii2-ckeditor-widget/blob/master/src/CKEditor.php#L51 

Modify that at will.
