### ISSUE TITLE
Missing widget plugin

### ISSUE THREAD

**Issue by tongtoanbs** [2amigos/yii2-ckeditor-widget#48]
I need an addon [widget](http://ckeditor.com/addon/widget) to install another external plugin. But I couldn't find this addon in ```vendor/2amigos/yii2-ckeditor-widget/src/assets/ckeditor/plugins``` and  [bower.io](http://bower.io/)

**Comment by tonydspaniard** [comment]
I think you need to download it your self. I have downloaded the official full version of ckeditor from its site and plugin is not shown. I need to investigate why it doesn't include all of them: https://github.com/ckeditor/ckeditor-dev/tree/master/plugins
