### ISSUE TITLE
CKEditor bar doesn't show

### ISSUE THREAD

**Issue by joostdr** [2amigos/yii2-ckeditor-widget#50]
When i try to add a field with a CKEditor, it doesn't show the bar. All it shows is a resizable text input window. (see image)

![ckeditor_img](https://cloud.githubusercontent.com/assets/9960306/10933990/09e13afc-82dd-11e5-87e6-b8639afb0ddb.png)

Code: 

    use dosamigos\ckeditor\CKEditor;
  
    $form = ActiveForm::begin() ?>  
    <?= $form->field($model, 'name')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic'
    ]) ?>
    <?php ActiveForm::end() ?>

**Comment by tonydspaniard** [comment]
What is the `console` output?
