### ISSUE TITLE
uncaught exception: The editor instance "w0" is already attached to the provided element.

### ISSUE THREAD

**Issue by msliman** [2amigos/yii2-ckeditor-widget#51]
I had this problem appeared in console.

**Comment by tonydspaniard** [comment]
mind sharing the code¿

**Comment by buttflattery** [comment]
@tonydspaniard , its when you use the `CKEditorInline` widget with the basic code given in the example on the github page, also it loads the jquery from the `adapter/jquery.js` and adds a dependency on `yii\web\JqueryAsset` too which results adding 2 jquery files.

**Comment by AndreyBCC** [comment]
For fixing it crate your widget which extends from CKEditorInline and implement  protected function registerPlugin() methow in which copy code of registerPlugin method but with commented row 
$js[] = "CKEDITOR.inline('$id', $options);";

This row duplicate creating editor instance
