### ISSUE TITLE
Updated CKeditor or use Bower

### ISSUE THREAD

**Issue by newerton** [2amigos/yii2-ckeditor-widget#54]
I'm having trouble with minification with this version.
Is the current version "4.5.6", already solves the problem CKEDITOR.getUrl ();

Sorry for my English.

**Comment by tonydspaniard** [comment]
@newerton thank you. I'll update as soon as possible.

**Comment by tonydspaniard** [comment]
@newerton do you mind testing 'master'? https://github.com/2amigos/yii2-ckeditor-widget/commit/0bf3527c825cd8f9a155f5c1cdf8fab576e00556 
if working then I'll update the tag version. Thanks.

**Comment by NabiKAZ** [comment]
Does I want to self update ckeditor?

**Comment by tonydspaniard** [comment]
@NabiKAZ do not understand...

**Comment by NabiKAZ** [comment]
I mean here: #64

**Comment by tonydspaniard** [comment]
Fixed on 2.0
