### ISSUE TITLE
Strange tooltip/ text appear when mouse hover on editor

### ISSUE THREAD

**Issue by hendrasyp** [2amigos/yii2-ckeditor-widget#55]
This is my code : <br/>
```
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\base\DynamicModel;
use dosamigos\ckeditor\CKEditor; 
?>

<?php 
$model = new \yii\base\DynamicModel(['cms_content']);
?>
<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'cms_content')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
    ]) ?>
<?php ActiveForm::end(); ?>
```
When I move cursor into textarea, **strange** tooltip are fired beside textarea ```Rich Text Editor, dynamicmodel-cms_content``` <br/> how could this happen ?

**Comment by hendrasyp** [comment]
![img-appear](https://cloud.githubusercontent.com/assets/15682267/12317272/29a79f26-bac2-11e5-999e-820b64f689cd.png)

**Comment by kankerlijer** [comment]
![image](https://cloud.githubusercontent.com/assets/10619287/12993290/8283d28c-d119-11e5-8cbe-0914c3e5812e.png)
I have somewhat the same issue. A tooltip is rendered with the id of editor? "nicer" lay out as OP but still... a user doesn't need to know html stuff.

**Comment by tonydspaniard** [comment]
@hendrasyp @kankerlijer Its very weird as i do use the editor and i do not have any tooltips. Maybe is due to the CMS theme you have? On another note, the label you show marked on the second image you need to remove it by setting it to false: 

```php
<?= $form->field($model, 'cms_content')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
    ])->label(false) ?>

**Comment by kankerlijer** [comment]
@tonydspaniard thanks for the reply. 
I allready tried label(false), this had no effect. 
using adminlte2 as theme.

**Comment by tonydspaniard** [comment]
@kankerlijer make sure is not due to the AdminLTE that you have those tooltips by default: https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#adminlte-options

**Comment by kankerlijer** [comment]
@tonydspaniard fixed it  :+1: 
I am such a noob, I should rtfm

**Comment by tonydspaniard** [comment]
great! :)

**Comment by hendrasyp** [comment]
great, you saved my code :)

thank's @tonydspaniard  :+1:
