### ISSUE TITLE
In Active Form on Submit send the html code

### ISSUE THREAD

**Issue by kshitizsingh** [2amigos/yii2-ckeditor-widget#6]
I was trying to use this repo using active form.
Editor was showing on screen. 
But when i enter data and submit the data then only normal text is posted to the action of active form. 
Is there is any way to access the html data of the editor on click submit.

**Comment by tonydspaniard** [comment]
bump

**Comment by kshitizsingh** [comment]
Still not corrected?

**Comment by tonydspaniard** [comment]
@kshitizsingh tested and working. Have you formatted the code written? ie bold

**Comment by mariyappan88** [comment]
Hi i'm getting error for this  use dosamigos\ckeditor\CKEditor;  how to give correct path? guys anyone know answer ?

**Comment by creocoder** [comment]
@mariyappan88 Can you provide more details?

**Comment by dynamicube** [comment]
Hi, sory for my bad english.
<p><span style="font-size:10px">test</span></p>,
this text not load model on server, on my local machine is running. Help. Thanks.
