### ISSUE TITLE
Require add Upload Image plugin

### ISSUE THREAD

**Issue by fengerzh** [2amigos/yii2-ckeditor-widget#61]
According to this official document, http://sdk.ckeditor.com/samples/fileupload.html, ckeditor introduced a new plugin named "Upload Image", address is here: http://ckeditor.com/addon/uploadimage . Can you please include this plugin in? Thanks!

**Comment by DarthLegiON** [comment]
I'd like to see this plugin in your widget too!

**Comment by tonydspaniard** [comment]
Do you mind making a PR? Make sure the tests pass and i'll merge it and update version patch. Thanks.

**Comment by nirvana-msu** [comment]
It is actually pretty straight-forward. Just follow the instructions on the [dev guide](http://docs.ckeditor.com/#!/guide/dev_file_upload) - download the plugin and all its dependencies. Register them as you would normally register external plugins. The response format has to be different from that of `filebrowser` plugin, but you can still use the same action/URL to submit the file to, just add e.g. `responseType=json` to the URL. In the controller action, respectively, you should format the response depending on whether you have `responseType` set to `json` or not, i.e. whether the image was uploaded through `uploadimage` or `filebrowser` plugin.

The only tricky bit is that you need to include CSRF token into the form that gets submitted. You can do that with the following js:

```
// We need the listener to be executed after filetools plugin opens XHR object as a POST request (priority 5),
// but before the default request is sent (priority 999), so e.g. priority 10 is fine.
CKEDITOR.on('instanceReady', function (ev) {
	ev.editor.on('fileUploadRequest', function (evt) {
		var fileLoader = evt.data.fileLoader,
			formData = new FormData();

		formData.append('upload', fileLoader.file, fileLoader.fileName);
		formData.append('ckCsrfToken', CKEDITOR.tools.getCsrfToken());  // Append CKEditor CSRF token
		formData.append(yii.getCsrfParam(), yii.getCsrfToken());        // Append Yii2 CSRF token
		fileLoader.xhr.send(formData);

		// Prevented default behavior.
		evt.stop();
	}, null, null, 10);
});
```

**Comment by WadeShuler** [comment]
I believe that this repo is dead. Maybe one day he will revive it.

Until then, please check out my repo: [https://github.com/WadeShuler/yii2-ckeditor-cdn](https://github.com/WadeShuler/yii2-ckeditor-cdn)

You will be able to update the version any time, on your own 👍 You just update the CDN URL, as it includes the specific version number.

This is a wrapper for the ckEditor library. By default, it uses the official CDN URL. That URL can be changed to be another CDN (Like CDNJS or AmazonS3, etc) or your own URL (download the library manually from the site and point to it). You can add plugins, skins, create presets, etc.

Best of all, you can use the configuration generated by the ckEditor Toolbar Configurator. I am not sure if this is possible with the 2amigos version? I had to convert it to an array to use it, PITA! Mine, you can build your config, save as a js file, and point to it :)

My version is a lot cleaner and future/update proof than this repo. I am hoping some of you can test it out, provide feedback, and it can become the go-to yii2 extension for using ckeditor.

**Comment by tonydspaniard** [comment]
https://github.com/2amigos/yii2-ckeditor-widget/blob/master/README.md#how-to-add-custom-plugins
