### ISSUE TITLE
allowedContent in options

### ISSUE THREAD

**Issue by StalkAlex** [2amigos/yii2-ckeditor-widget#65]
Hello, is this code suppose to work?
```
<?= $form->field($model, 'value')->widget(CKEditor::className(), [
                'options' => [ 'allowedContent' => true ],
                'preset' => 'full',
  ]) ?>
```
I want a possibility to insert custom tags during edititng. And this code is not working, editor still removes all unstandard tags.

**Comment by tonydspaniard** [comment]
instead of `options` use `clientOptions`: https://github.com/2amigos/yii2-ckeditor-widget/blob/master/src/CKEditorTrait.php#L39
