### ISSUE TITLE
Bad Request (#400) - Unable to verify your data submission

### ISSUE THREAD

**Issue by mahsa92** [2amigos/yii2-ckeditor-widget#68]
Hi!
I have a problem when i want to add a file and an image to a text with ckeditor.
It uploads file correctly but when i want to upload my image, I get bad request error.
I traced the code and found that  registerCsrfImageUploadHandler function runs just once and it doesn't run in uploading image.
Whats the problem?
How I can fix it?

**Comment by nirvana-msu** [comment]
The extension currently does not deal with multiple widgets appropriately. The code snippet in my [post here](https://github.com/2amigos/yii2-ckeditor-widget/issues/2#issuecomment-237703590) should solve your problem.

**Comment by tonydspaniard** [comment]
@mahsa92 this was already solved: https://github.com/2amigos/yii2-ckeditor-widget/pull/72
