### ISSUE TITLE
add spolier

### ISSUE THREAD

**Issue by des1roer** [2amigos/yii2-ckeditor-widget#69]
how i can add spoiler?

**Comment by tonydspaniard** [comment]
We will have to create a PR and add the plugin to the plugins folder: https://github.com/2amigos/yii2-ckeditor-widget/tree/master/src/assets/ckeditor/plugins then is simply adding its name to `extraPlugins`. I'll put it on my 'todo' but a pull request is always welcome.

**Comment by des1roer** [comment]
on index 

$this->registerJsFile('/ckeditor/plugins/config.js',  ['position' => '\yii\web\View::POS_END']);
$this->registerCssFile('/ckeditor/plugins/include/spoiler.css');


config.js

CKEDITOR.plugins.basePath = '/ckeditor/plugins/';

CKEDITOR.editorConfig = function( config ) {
config.extraPlugins = 'spoiler';
};

all project
[yii2tree.zip](https://github.com/2amigos/yii2-ckeditor-widget/files/484226/yii2tree.zip)

**Comment by tonydspaniard** [comment]
Thanks @des1roer

**Comment by tonydspaniard** [comment]
Fixed on version 2.0: https://github.com/2amigos/yii2-ckeditor-widget#how-to-add-custom-plugins
