### ISSUE TITLE
ckeditor 4.4.7

### ISSUE THREAD

**Issue by nailfor** [2amigos/yii2-ckeditor-widget#71]
after run 
`composer require 2amigos/yii2-ckeditor-widget:~1.0`
i got src/ckerditor with 4.4.7 version, but rep has 4.5.7

how can I fix it?

**Comment by WadeShuler** [comment]
I believe that this repo is dead. Maybe one day he will revive it.

Until then, please check out my repo: [https://github.com/WadeShuler/yii2-ckeditor-cdn](https://github.com/WadeShuler/yii2-ckeditor-cdn)

You will be able to update the version any time, on your own 👍 You just update the CDN URL, as it includes the specific version number.

This is a wrapper for the ckEditor library. By default, it uses the official CDN URL. That URL can be changed to be another CDN (Like CDNJS or AmazonS3, etc) or your own URL (download the library manually from the site and point to it). You can add plugins, skins, create presets, etc.

Best of all, you can use the configuration generated by the ckEditor Toolbar Configurator. I am not sure if this is possible with the 2amigos version? I had to convert it to an array to use it, PITA! Mine, you can build your config, save as a js file, and point to it :)

**Comment by tonydspaniard** [comment]
I need to update ckeditor version. Will try to find out whether I can now use full version throughout composer this time.

**Comment by nailfor** [comment]
Hello
But i don't understand how you connect chkeditor? I must have chkeditor
instance in my project?

2016-09-20 18:29 GMT+03:00 Wade Shuler <notifications@github.com>:

**Comment by tonydspaniard** [comment]
@nailfor not sure i understand how do  I connect CKEditor. I used to have the full version. Working right now on an updated version.

**Comment by tonydspaniard** [comment]
Fixed on 2.0, now works with latest on their packagist: https://github.com/2amigos/yii2-ckeditor-widget/blob/master/composer.json#L30
