### ISSUE TITLE
Add CDN Support and improve README

### ISSUE THREAD

**Issue by WadeShuler** [2amigos/yii2-ckeditor-widget#73]
This projects seems to be partially abandoned. However, it's worth a shot.

There should be a CDN option. Whether you have to specify the version number in the config, or specify the CDN root URL that includes the version number.

You could do: https://cdnjs.com/libraries/ckeditor
Then have them also specify the version: 4.5.10

or

Just have them specify the CDN root URL: https://cdnjs.com/libraries/ckeditor/4.5.10

---

For the non-CDN use (using assets as it currently does), a "use CDN for smilies" option would be nice. In the Advanced template, if you have the editor in the backend for admin use, the frontend uses the backend's `assets` directory because it stores it's current path (backend) for the smiley in the db. Revealing the path to your admin area is bad security practice. While not everyone uses the advanced for this, most DO use the `backend` for admin purposes.

---

Additionally, some basic usage help should be added to the README. It took a bit of research, and trial and error, to get this set up. You provide 0 setup other than simply how to install the plugin.

Here is my current widget:

    $ckToolbarTemplate = [
        ['name' => 'document', 'groups' => ['mode', 'document', 'doctools']],
        ['name' => 'clipboard', 'groups' => ['clipboard', 'undo']],
        ['name' => 'editing', 'groups' => [ 'find', 'selection', 'spellchecker', 'editing']],
        ['name' => 'basicstyles', 'groups' => ['basicstyles', 'colors','cleanup']],
        '/',
        ['name' => 'paragraph', 'groups' => [ 'list', 'indent', 'blocks', 'align' ]],
        ['name' => 'links'],
        ['name' => 'insert'],
        '/',
        ['name' => 'styles'],
        ['name' => 'colors'],
        ['name' => 'tools'],
        ['name' => 'others'],
    ];

    $ckRemoveButtons = 'NewPage,Flash,Iframe,SpecialChar';

    <?= $form->field($model, 'text')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'custom',
        'clientOptions' => [
            'toolbarGroups' => $ckToolbarTemplate,
            'removeButtons' => $ckRemoveButtons,
            'smiley_path' => '//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.10/plugins/smiley/images/'
        ]
    ]) ?>

You didn't show how to change the preset (basic, standard, full, custom), or that the `clientOptions` even exists, how to modify the toolbar items, handle smileys, or image/file uploads.

I still want to remove my large array and make it a config file to load, but I don't know if it is possible with your extension. For `preset`, I saw in the code that it includes the corresponding file. ie: `basic` includes the `basic.php` config. However, if preset is custom, it sets it to null.

**Comment by jeesus** [comment]
This extension needs an update in general. Could include new skins and require the original source directly via composer. Is there going to be any update soon or is this project abandoned (as you can tell from comments)?

**Comment by WadeShuler** [comment]
This repo looks dead IMO.

Please check out my version of ckEditor for Yii2: [https://github.com/WadeShuler/yii2-ckeditor-cdn](https://github.com/WadeShuler/yii2-ckeditor-cdn)

By default, it uses the official CDN, but it's URL can be overridden to use any url (either another CDN like CDNJS or your own copy). You can install plugins, skins, etc. I created it with the ability to do anything/everything the real editor can do. I have no idea why 2amigos wrote his own JS script and pass it through his own functions. I think he made it clunky, so I have set it free 👍 

Please note, I wrote this while in the middle of a project that needed the ckEditor. I can tell you, that in my setup, it works just fine :) I did install a plugin and a skin, worked fine for me. However, I would call it a **beta** as it has not been battle tested. Please test it, and leave an issue on **my repo not here**. I am not trying to get all fancy, but just make it a wrapper for the original library.

**Comment by tonydspaniard** [comment]
@jeesus the problem is that the original repo with composer is not installing the full version. Nevertheless, I am fully open for PRs.

**Comment by tonydspaniard** [comment]
@jeesus all fully updated

**Comment by jeesus** [comment]
@tonydspaniard I still cannot use Full version of the editor. As before, only updated through composer. Currently using version 2.0.1.

**Comment by muhibuddin12** [comment]
jj
