### ISSUE TITLE
Show source button in 'preset' => 'basic',

### ISSUE THREAD

**Issue by shahzadthathal** [2amigos/yii2-ckeditor-widget#74]
Hi,

How I can show view source button in toolbar, I'm using basic editor?

Thanks

**Comment by tonydspaniard** [comment]
Have you tried to update using 'clientOptions' for custom toolbar configuration?

**Comment by baltechies** [comment]
Hi,
I have followed the **How to add custom plugins** documentation as you mentioned, to add the extra plugin sourcearea. But button is not visible in toolbaar.
