### ISSUE TITLE
registerCsrfImageUploadHandler() not registered / called if filebrowserImageUploadUrl is defined

### ISSUE THREAD

**Issue by techie42** [2amigos/yii2-ckeditor-widget#76]
In CKEditor.php, if we define filebrowserImageUploadUrl (instead of filebrowserUploadUrl), then the CSRF is never added to the upload data.

In the CKEditor docs, filebrowserUploadUrl defines a generic upload routine and filebrowserImageUploadUrl defines a specific image upload routine.

I would suggest the code is modified as follows (around line 68 of CKEditor.php):

Original:
`        if (isset($this->clientOptions['filebrowserUploadUrl'])) {
            $js[] = "dosamigos.ckEditorWidget.registerCsrfImageUploadHandler();";
        }
`

Revision:
`        if (isset($this->clientOptions['filebrowserUploadUrl']) || isset($this->clientOptions['filebrowserImageUploadUrl'])) {
            $js[] = "dosamigos.ckEditorWidget.registerCsrfImageUploadHandler();";
        }
`
This solves the issue and specific image uploads occur normally.

Also, CKEditorInline.php would also need to be modified accordingly around line 90, replacing the same code shown above with the revision.

**Comment by WadeShuler** [comment]
I believe that this repo is dead. Maybe one day he will revive it.

Until then, please check out my repo: [https://github.com/WadeShuler/yii2-ckeditor-cdn](https://github.com/WadeShuler/yii2-ckeditor-cdn)

I would disable CSRF with his extension. He uses some custom javascript for handling this, and it is clunky.

Mine, you can update at any time. Just change the CDN URL :)

This is a wrapper for the ckEditor library. By default, it uses the official CDN URL. That URL can be changed to be another CDN (Like CDNJS or AmazonS3, etc) or your own URL (download the library manually from the site and point to it). You can add plugins, skins, create presets, etc.

Best of all, you can use the configuration generated by the ckEditor Toolbar Configurator. I am not sure if this is possible with the 2amigos version? I had to convert it to an array to use it, PITA! Mine, you can build your config, save as a js file, and point to it :)

My version is a lot cleaner and future/update proof than this repo. I am hoping some of you can test it out, provide feedback, and it can become the go-to yii2 extension for using ckeditor.

**Comment by tonydspaniard** [comment]
I'll have a look at your amazing extension. Looks awesome hope is not clunky Mr nice guy... But this repo is not dead and surely run by gentlemen.

**Comment by tonydspaniard** [comment]
@techie42 do you have time for a quick PR? I'll review it whenever i have time. Thanks

**Comment by WadeShuler** [comment]
Issues piling up and nothing for what looks to be MONTHS. Every tall tale sign that the repo was dead. I get it, it is open source, it's GitHub, and you owe nobody to maintain the repo. However, I think there was some motive to you popping up today and tackling some of the issues.

Clunky is because of the javascript file, `dosamigos-ckeditor.widget.js`.

**Comment by techie42** [comment]
Sorry it's taken so long ... but finally done :)  Thanks for your patience.
