### ISSUE TITLE
syntax error, unexpected '.', expecting ',' or ';'

### ISSUE THREAD

**Issue by simone86** [2amigos/yii2-ckeditor-widget#79]
in /Applications/MAMP/htdocs/4pro/vendor/2amigos/yii2-ckeditor-widget/src/CKEditorWidgetAsset.php at line 21 

class CKEditorWidgetAsset extends AssetBundle
{
    public $sourcePath = **DIR** . '/assets';

........

**Comment by abondr** [comment]
use this way 

public $sourcePath =  './../assets';
[by r]

**Comment by tonydspaniard** [comment]
@simone86 do you mind testing on master branch?

**Comment by tonydspaniard** [comment]
@simone86 nevertheless, this is wrong: 

```php 
public $sourcePath = DIR . '/assets';
```

Should be 
```php 
public $sourcePath = __DIR__ . '/assets';
```

What is the version you have?

**Comment by abumaryam** [comment]
I have same problem. and I replaced it like this:
public $sourcePath =  '@vendor/2amigos/yii2-ckeditor-widget/src/assets';

**Comment by aripjanovsh** [comment]
i have error too on PHP 5.5, but on PHP 5.6 and PHP 7 i dont have error message

**Comment by TomasTarasovic** [comment]
Will be last release compatible with php 5.5 ?

**Comment by felladrin** [comment]
Same problem here.
@abumaryam's solution has made the trick. Thanks!

**Comment by pptyasar** [comment]
I have same problem. Is issue fixed???

**Comment by tonydspaniard** [comment]
@pptyasar @felladrin @abondr @aripjanovsh @simone86 It should be fixed: `public $sourcePath = '@vendor/2amigos/yii2-ckeditor-widget/src/assets/';` was added.
