### ISSUE TITLE
only standard preset working after update to 2.* version

### ISSUE THREAD

**Issue by akulyk** [2amigos/yii2-ckeditor-widget#80]
got a problem with preset settings

$form->field($model, 'short_desc')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full',
        //'skin'=>'moono',
        'enableKCFinder' => true,
    ]) 
but only standard toolbar shows

**Comment by akulyk** [comment]
![2016-09-24 17 33 57](https://cloud.githubusercontent.com/assets/7733585/18809112/1f8e89ae-827d-11e6-9afb-89205cc36637.png)

**Comment by tonydspaniard** [comment]
@akulyk do you mind testing on master branch?

**Comment by tonydspaniard** [comment]
@akulyk by the way... I think you are not using this extension: 

```php 
'enableKCFinder' => true,
```

That property is not from here.

**Comment by akulyk** [comment]
well 'enableKCFinder' => true, maybe not, but I have only updated my project by composer and got this.
With version 1.0.4, all good

**Comment by tsanchev** [comment]
After updating the widget to the latest version i have this error:
`Invalid Parameter – yii\base\InvalidParamException`
`Trying to copy a directory to itself or a subdirectory.`

Tracing error down the stack

- `CKEditorWidgetAsset::register($view);`
- `$this->registerPlugin();`

**Comment by tonydspaniard** [comment]
@tsanchev do you mind trying the lastest on master branch and check whether that stills happening?

**Comment by tsanchev** [comment]
@tonydspaniard still the same same error

**Comment by HanafiAhmat** [comment]
Hi @tonydspaniard ,

I tried using master branch but i got the error described in https://github.com/2amigos/yii2-ckeditor-widget/issues/79.

Based on this commit, https://github.com/2amigos/yii2-ckeditor-widget/commit/11deb530ab77fc91f89a444fd973d1e88dd67fb4, CKEditorWidgetAsset init function was removed and $sourcePath value assignment was done on class attribute declaration.

Maybe value concatenation can be done when assigning it to an attribute there on php 5.6 and above.
As mentioned by @aripjanovsh, he encountered the syntax error when he used php 5.5. I am using php 5.4.

After removing line 21 `public $sourcePath = __DIR__ . '/assets';` and added init function 
```
    public function init()
    {
        $this->sourcePath = __DIR__ . '/assets';
        parent::init();
    }
```
`Invalid Parameter – yii\base\InvalidParamException` is gone.

After implementing the init function, presets work as per normal.

**Comment by jeesus** [comment]
Same problem over here. Full and standard preset look exactly the same, lacking even elementary alignment buttons.

**Comment by tonydspaniard** [comment]
Checking...

**Comment by jeesus** [comment]
@tonydspaniard check my answer [here](https://github.com/2amigos/yii2-ckeditor-widget/issues/87#issuecomment-264156570).

**Comment by tonydspaniard** [comment]
Thanks @jeesus. Updating the library.

**Comment by tonydspaniard** [comment]
@akulyk @jeesus @HanafiAhmat @tsanchev please guys, update to latest and let me know if it works for you. Thanks!
