### ISSUE TITLE
Does not work on android devices (on ios haven't tested)

### ISSUE THREAD

**Issue by dimaraduk91** [2amigos/yii2-ckeditor-widget#82]
Works on PC and possible IOS as showed "toggle device toolbar" in Crome.
`<?= $form->field($model->node, 'description')->widget(CKEditor::className(), [                 
                    'options' => ['rows' => 6],
                    'preset' => 'custom',
                    'clientOptions' => [
                        'toolbarGroups' => $ckToolbarTemplate,
                        'removeButtons' => $ckRemoveButtons,
                        'smiley_path' => '//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.10/plugins/smiley/images/'
                    ]
                ])->label(false) ?>`

**Comment by tonydspaniard** [comment]
http://ckeditor.com/forums/CKEditor/Enabling-ckEditor-on-Android-Phone
