### ISSUE TITLE
Does not display correctly

### ISSUE THREAD

**Issue by midcore-nam** [2amigos/yii2-ckeditor-widget#83]
It doesn't display correctly. This is the modal and it was working before the update.
![image](https://cloud.githubusercontent.com/assets/16084009/19152811/c3c9dffa-8ba1-11e6-94f0-2c9c40c14f40.png)

here is the code in my view:

$form->field($model, 'DefaultValue', ['enableAjaxValidation' => true])->widget(CKEditor::className(), [
                        'options' => ['rows' => 6],
                        'clientOptions' => ['removePlugins' => 'elementspath,save,font,link,image'],
                        'preset' => 'basic',
                    ])->label(false);

**Comment by CyanoFresh** [comment]
How do you fix it?
