### ISSUE TITLE
Format text

### ISSUE THREAD

**Issue by TomasTarasovic** [2amigos/yii2-ckeditor-widget#84]
Please I have version "2amigos/yii2-ckeditor-widget" : "^1.0", and format plugin is not working. Is it problem, because of version ? Or format should be work correct ? I don't have idea why it not working.

**Comment by tonydspaniard** [comment]
do you mind trying "^2.0" instead and tell me if it works for you? In addition, it would be nice if you could paste some code so I could see where the issue lies. Thanks!
