### ISSUE TITLE
toolbarGroups settings not work with version 2.0.0

### ISSUE THREAD

**Issue by yangtoude** [2amigos/yii2-ckeditor-widget#87]
Hi @tonydspaniard got a problem with toolbarGroups settings

```
    'widgetOptions' => [
        'class' => '\dosamigos\ckeditor\CKEditor',
        'preset' => 'custom',
        'clientOptions' => [
            'allowedContent' => true,
            'extraPlugins' => 'lineheight,uploadimage',
            'line_height' => '1;1.2;1.5;2;2.5;3',
            'imageUploadUrl' => '/accelerator/upload',
            'toolbarGroups' => [
                ['name' => 'forms'],
                ['name' => 'others'],
            ],
        ],
    ]
```

but only standard toolbar shows, the toolbarGroups settings just not work
![screen shot 2016-10-09 at 5 56 06 pm](https://cloud.githubusercontent.com/assets/17309758/19219589/c2b6fba2-8e49-11e6-8b5f-b36864f39db9.png)

**Comment by CyanoFresh** [comment]
+1

**Comment by yangtoude** [comment]
Hi, @tonydspaniard  I found that I can add button by adding extra plugins, for example colorbutton.
Does mean that I have to add button by adding extra plugins since version 2.0.0? By the way, toolbarGroups still not work. Here is my widget options:
```
'widgetOptions' => [
    'class' => '\dosamigos\ckeditor\CKEditor',
    'preset' => 'full',
    'clientOptions' => [
        'allowedContent' => true,
        'extraPlugins' => 'lineheight,uploadimage,colorbutton',
        'line_height' => '1;1.2;1.5;2;2.5;3',
        'imageUploadUrl' => '/accelerator/upload',
    ],
]
```

**Comment by CyanoFresh** [comment]
Changing the config.js and presets/full.php doesn't work

**Comment by tonydspaniard** [comment]
Dear @yangtoude I'll have a look at it... Thank you for the description

**Comment by tonydspaniard** [comment]
@yangtoude according to the information http://docs.ckeditor.com/#!/guide/dev_toolbarconcepts-section-toolbar-groups-configuration you don't seem to have it correctly. What you need to do is to define your `toolbar` setting and then use the `['name' => 'GROUPNAME', 'items' => ['your items']`

**Comment by jeesus** [comment]
Same problem here, standard and full preset look exactly the same, even elementary alignment buttons are missing.

**Comment by jeesus** [comment]
The problem lies in the composer.json of this project. According to [CKEditor docs](http://docs.ckeditor.com/#!/guide/dev_package_managers), the composer's require part should look like this in order to get the full package:
```
{
    "require": {
        "ckeditor/ckeditor": "dev-full/stable"
    }
}
```

**Comment by tonydspaniard** [comment]
@yangtoude @jeesus @CyanoFresh I have updated adding the dev-full, mind updating to 2.0.2 and tell me if it works for you guys? Thanks

**Comment by CyanoFresh** [comment]
will check as soon as I have some time

**Comment by CyanoFresh** [comment]
@tonydspaniard now works good. But composer chose 2.0.1 version, maybe stability issue. Thanks

**Comment by tonydspaniard** [comment]
@CyanoFresh great! Thank you for the feedback. Could be some requirements... I'll check that.
