### ISSUE TITLE
syntax error, unexpected '.', expecting ',' or ';'

### ISSUE THREAD

**Issue by sauravsuman1** [2amigos/yii2-ckeditor-widget#88]
Version :: ^2.0
vendor/2amigos/yii2-ckeditor-widget/src/CKEditorWidgetAsset.php  :: line 21

Got this error on first time use.

Resolve this by changing the original code 
###### ####################### ORIGINAL CODE

`class CKEditorWidgetAsset extends AssetBundle
{
    public $sourcePath = **DIR** . '/assets';

```
public $depends = [
    'dosamigos\ckeditor\CKEditorAsset'
];

public $js = [
    'dosamigos-ckeditor.widget.js'
];
```

}`
###### ##################### NEW CODE

class CKEditorWidgetAsset extends AssetBundle
{
    public $sourcePath;

```
public $depends = [
    'dosamigos\ckeditor\CKEditorAsset'
];

public $js = [
    'dosamigos-ckeditor.widget.js'
];

public function init(){
    $this->sourcePath = __DIR__ . '/assets';
}
```

}

**Comment by maan81** [comment]
Same error.

**Comment by ipppinto** [comment]
Me too.

The code have to change to:

class CKEditorWidgetAsset extends AssetBundle
{
public $sourcePath;

public $depends = [
    'dosamigos\ckeditor\CKEditorAsset'
];

public $js = [
    'dosamigos-ckeditor.widget.js'
];

public function init(){
    $this->sourcePath = __DIR__ . '/assets';
}
}

**Comment by nicosavini** [comment]
Me too. Only in production server. Probably something to do with PHP config, but I believe it's better if it's fixed from source as it can be easily solved.

**Comment by tonydspaniard** [comment]
@nicosavini do you mind checking master? A contribution may have fixed the issue.

**Comment by nicosavini** [comment]
Seems to be working now.

**Comment by tonydspaniard** [comment]
Good! I will update the version then...

**Comment by beatcode** [comment]
Same with PHP 5.5.14
