### ISSUE TITLE
Skins folder isn't loaded in web/assets/

### ISSUE THREAD

**Issue by midcore-nam** [2amigos/yii2-ckeditor-widget#89]
I received GET 404 errors with skins/moono/editor.css and styles.js

![image](https://cloud.githubusercontent.com/assets/16084009/19730733/25ffabb0-9b69-11e6-9261-bee1c4ddf04f.png)

**Comment by midcore-nam** [comment]
update to latest yii 2.0.10 fixed the issue.

**Comment by ak868308** [comment]
I have same issue please help
