### ISSUE TITLE
Not working when assets get cleared 

### ISSUE THREAD

**Issue by ak868308** [2amigos/yii2-ckeditor-widget#92]
I was cleared all the assets from assests dir because want to to load new assets.
But after that CKEditor surprised me. It shows an error please see attach 
![ckeditor](https://cloud.githubusercontent.com/assets/7982249/20647154/c4318af8-b4b2-11e6-893f-7c8f96e49c8d.PNG)

**Comment by midcore-nam** [comment]
same here.

**Comment by tonydspaniard** [comment]
@ak868308 @midcore-nam Do you mind updating to latest 2.0.2 and tell me if it works for you? Is your "localhost" the correct url? Thanks!

**Comment by midcore-nam** [comment]
yes, localhost. I've noticed something, it does that when i was working with master branch only. When i switch to different branch, delete the asset folder, it regenerates everything correctly. :)

**Comment by MUTOgen** [comment]
the same for me too
how to fix it?

**Comment by tonydspaniard** [comment]
@MUTOgen seems there is a miss-configuration on the packages. Have you double check the bundle configuration on minify?

**Comment by midcore-nam** [comment]
this is happening again.

**Comment by tonydspaniard** [comment]
No more info given. Closing this issue.

**Comment by asaenzestrada** [comment]
This was cleared in this issue: https://github.com/rmrevin/yii2-minify-view/issues/38 @tonydspaniard #

**Comment by tonydspaniard** [comment]
Thank you @asaenzestrada
