### ISSUE TITLE
Additional parameters have no effect

### ISSUE THREAD

**Issue by dmitri-s** [2amigos/yii2-ckeditor-widget#93]
After running a composer update the plugin no longer allow you to set preset to full.
`'preset' => 'full',`
Setting it to **full**, **standard** or **basic** has no effect.

Also tried setting options->rows to 1,5,6,10,15,20 and had no effect on end form.
`'options' => ['rows' => 6],`

```
<?= $form->field($model, 'text')->widget(CKEditor::className(), [
                options' => ['rows' => 6],
                'preset' => 'full', ])
?>
```

Please advice.

**Comment by tonydspaniard** [comment]
Do you mind testing against the 'master' branch? Maybe I missed to tag version.

**Comment by dmitri-s** [comment]
I am not composer guru. Been using Yii2 and composer for last few month. So if I am doing something wrong feel free to point it out and I will re-test.

Here is what I did:
1. Change composer.json to include "2amigos/yii2-ckeditor-widget": "dev-master" under require.
- That resulted in composer throwing an error that package does not satisfy minimal stability [dev-full/stable].
2. I tried to select last commit this way:   "2amigos/yii2-ckeditor-widget": "dev-master#60e4d2dbb138706c8c2195a1b29c420bda044b19" under requre.
- That resulted in the same error. 
3. Changed minimal-stability to dev.
- That resulted in composer installing 2amigos/yii2-ckeditor-widget (dev-master 60e4d2d). Which is matches last commit listed in github from Dec 1, 2016.
(n.b. There were many other Yii2 packages that were updated as well. Could potentially skew results of the tests)
Performed the following tests:
```
<?= $form->field($model, 'text')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'full',
])?>
```
Full shows up correctly:
![image](https://cloud.githubusercontent.com/assets/14946356/21021075/095309e6-bd45-11e6-947e-8250b051c056.png)

```
<?= $form->field($model, 'rts_dist_assigment')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'standard',
])?>
```
Standard shows up correctly:
![image](https://cloud.githubusercontent.com/assets/14946356/21021146/4b48357e-bd45-11e6-8587-cda1a890c0b3.png)

```
<?= $form->field($model, 'rts_dist_assigment')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'basic',
])?>
```
Basic shows up correctly:
![image](https://cloud.githubusercontent.com/assets/14946356/21021230/9102a9a0-bd45-11e6-9a09-1f32015f7e02.png)

So option preset working as expected. 

One the other hand `'options' => ['rows' => 6],` still does not have any effect on the widget. Selecting 1, 6, 10, or 600 will result in the same window size. Will not bore you with screenshots.

**Comment by tonydspaniard** [comment]
@dmitri-s thanks for such great feedback. About the rows, I believe that you need to use the "height" attribute in `clientOptions` to change the size of the editor. Remember we are using the underline plugin, modifying the textarea attributes have no effect.

**Comment by Azam2926** [comment]
I like full of preser

**Comment by tonydspaniard** [comment]
@Azam2926 have you tried this? 

```
<?= $form->field($model, 'attributeName')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'full', // <---- HERE
])?>
