### ISSUE TITLE
Item 'Underline' is not showing

### ISSUE THREAD

**Issue by jaehter** [2amigos/yii2-ckeditor-widget#94]
I choosed custom configuration without toolbarGroups and I didn´t get the item 'Underline' in the toolbar.

`<?= $form->field($model, 'text')->widget(CKEditor::className(), [
                'preset' => 'custom',
                'clientOptions' => [
                    'height' => 400,
                    'toolbar' => [
                        ['name' => 'undo', 'items' => ['Undo', 'Redo']],
                        ['name' => 'basicstyles', 'items' => ['Bold', 'Italic', 'Underline']],
                        ['name' => 'list', 'items' => ['NumberedList', 'BulletedList']],
                    ]
                ]
            ]) ?>`

Anyone knows what´s wrong?

**Comment by tonydspaniard** [comment]
maybe you should do this?

```
 ['name' => 'basicstyles', 'groups' => ['basicstyles'],
```

**Comment by tonydspaniard** [comment]
@jaehter please check this: http://ckeditor.com/comment/122939#comment-122939
