### ISSUE TITLE
'Iframe' is not showing in toolbar

### ISSUE THREAD

**Issue by samirreza** [2amigos/yii2-ckeditor-widget#98]
Im choosing custom configuration for toolbar but I cant see Iframe button in toolbar
`        [
            'name' => 'row2',
            'items' => [
                'Bold', 'Italic', 'Underline', '-',
                'TextColor', 'BGColor', '-',
                'Image', 'Link', 'Unlink', 'Anchor',
                'FontSize', 'Format', '-',
                'Templates', '-',
                'RemoveFormat',
                'Print',
                'Iframe',
                'ShowBlocks',
                'pspell',
            ],
        ],`
but when i switch to prior version of this repo I can see this button

**Comment by tonydspaniard** [comment]
Don't you need the extra plugin? http://ckeditor.com/addon/iframe

**Comment by tonydspaniard** [comment]
No more info given. Closing this issue.
